logger:
    output_file: 'log.log'

presentmon:
    output_file: 'pm.csv'

perfomance_tracker:
    output_file: 'stat.csv'

kkrieger:
    process_name: 'pno0001.exe'
    base_addres: 0x7c0000
    gm_buffer_pointer: 0x00398594
    gm_off: [0x8, 0x1348, 0x4, 0x4, 0x1C]
